### ISSUE TITLE
pip-Command not working when using backup (minor inconvinience)

### ISSUE THREAD

**Issue by robinhood1596** [fredrikbaberg/ha-3dprinter-addons#84] opened 2023-12-02 13:08 UTC
### Describe the issue you are experiencing

When installing the add-on in HAOS and then configuring the server with a backup, plugins can't be installed due to "pip command not working properly or not being found". If installing and then configuring manually it orks just fine.

### Which add-on are you reporting an issue with?

3DPrinter-OctoPrint

### What is the version of the add-on?

Latest, 1.9.3 for Octoprint

### Steps to reproduce the issue

1. Install add-on
2. Update Octoprint to latest version
3. Setup with backup (that had plug-ins)
4. Try to install or uninstall plug ins --> pip not working as message
...

### Anything in the add-on logs that might be useful?

```txt
2023-12-01 17:13:12,442 - sarge - WARNING - No process found for Command('D:\\OctoPrintWin\\WPy64-31050\\python-3.10.5.amd64\\Scripts\\pip.exe --version')
2023-12-01 17:13:12,443 - octoprint.util.pip - ERROR - Error while discovering pip command


2023-12-01 15:44:34,316 - octoprint.util.pip - ERROR - Error while discovering pip command
Traceback (most recent call last):
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 668, in run
    self.process = p = Popen(self.args, **self.kwargs)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\OctoPrintWin\\WPy64-31050\\python-3.10.5.amd64\\Scripts\\pip.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 292, in trigger_refresh
    self._setup_pip()
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 334, in _setup_pip
    pip_version, version_segment = self._get_pip_version(pip_command)
  File "/data/python/octoprint/lib/python3.9/site-packages/octoprint/util/pip.py", line 459, in _get_pip_version
    p = sarge.run(
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 1481, in run
    p.run(input=input, async_=async_)
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 1088, in run
    self.run_node(node, input=input, async_=False)
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 1206, in run_node
    result = getattr(self, method)(node, input, async_)
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 1352, in run_command_node
    node.cmd.run(input=input, async_=async_)
  File "/data/python/octoprint/lib/python3.9/site-packages/sarge/__init__.py", line 671, in run
    raise ValueError('Command not found: %s' % self.args[0])
ValueError: Command not found: D:\OctoPrintWin\WPy64-31050\python-3.10.5.amd64\Scripts\pip.exe
```

### Additional information

Backup came from a windows installed server? Maybe thats te problem? 

Tried it twice with the same backup and didn't work

**Comment by fredrikbaberg** [comment] 2024-01-02 13:45
I plan to bring my install up this or next week, will have a look then.

**Comment by fredrikbaberg** [comment] 2024-01-21 21:48
Most likely since it's from Windows, but I am still not sure why an OctoPrint backup would need the pip path. It's not something I've found in my backups so far.

**Comment by fredrikbaberg** [comment] 2024-02-18 08:06
Closing this as I'm unable to reproduce.

I installed OctoPrint in a virtual environment in Windows, installed three plugins (Bed Visualizer, PrintTimeGenius, Dashboard), created a backup and restored it in the add-on without issue.

**Closed by fredrikbaberg** 2024-02-18 08:06 UTC
